apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skool-mvp-observability
  namespace: argocd
  labels:
    app: skool-mvp-observability
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.4.0
    helm:
      values: |
        global:
          scrape_interval: 15s
        prometheus:
          service:
            type: ClusterIP
        grafana:
          enabled: true
          service:
            type: LoadBalancer
        alertmanager:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
